export const UPDATE_MATCHES = 'UPDATE_MATCHES';
export const SET_CURRENT_MATCH = "SET_CURRENT_MATCH";
export const SET_CURRENT_TRACKS = "SET_CURRENT_TRACKS";
export const SET_CURRENT_IMAGES = "SET_CURRENT_IMAGES";

export const LOADING = "LOADING";

export const ADD_LIKE = "ADD_LIKE";
export const REMOVE_LIKE = "REMOVE_LIKE";
export const UPDATE_LIKES = "UPDATE_LIKE";
