export const UPDATE_MATCHES = 'UPDATE_POSTS';
export const SET_CURRENT_MATCH = "SET_CURRENT_POST";

export const LOADING = "LOADING";

export const ADD_LIKE = "ADD_FAVORITE";
export const REMOVE_LIKE = "REMOVE_FAVORITE";
export const UPDATE_LIKES = "UPDATE_FAVORITES";

export const SET_NAVIGATION = "SET_NAVIGATION";